"""Description of migration

Revision ID: 11cec1d6c9df
Revises: 93b49a53f1f4
Create Date: 2024-05-15 18:54:28.323013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11cec1d6c9df'
down_revision: Union[str, None] = '93b49a53f1f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mymodel', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mymodel', 'address')
    # ### end Alembic commands ###
