"""Description of migration

Revision ID: 47da18dd5fef
Revises: 7c01b4fbe985
Create Date: 2024-05-16 13:37:53.908416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47da18dd5fef'
down_revision: Union[str, None] = '7c01b4fbe985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mymodel', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mymodel', 'address')
    # ### end Alembic commands ###
