"""Description of migration

Revision ID: bc83ef3c2401
Revises: 47da18dd5fef
Create Date: 2024-05-17 12:07:37.344011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc83ef3c2401'
down_revision: Union[str, None] = '47da18dd5fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mymodel', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mymodel', sa.Column('address', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
