"""Added business process

Revision ID: 1e360250fbb4
Revises: 819cbf6e030b
Create Date: 2024-05-14 16:51:49.617893

"""
import sqlalchemy as sa
from alembic import op
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision = "1e360250fbb4"
down_revision = "819cbf6e030b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_processes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("process_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_business_processes_description"),
        "business_processes",
        ["description"],
        unique=False,
    )
    op.create_index(
        op.f("ix_business_processes_id"), "business_processes", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_business_processes_name"), "business_processes", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_business_processes_status"),
        "business_processes",
        ["status"],
        unique=False,
    )
    op.create_table(
        "user",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_business_processes_status"), table_name="business_processes")
    op.drop_index(op.f("ix_business_processes_name"), table_name="business_processes")
    op.drop_index(op.f("ix_business_processes_id"), table_name="business_processes")
    op.drop_index(
        op.f("ix_business_processes_description"), table_name="business_processes"
    )
    op.drop_table("business_processes")
    # ### end Alembic commands ###
